language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - DB=mysql

before_script:
    - composer install
    - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS raw_options_test;" -uroot; fi

script: phpunit --configuration tests/phpunit.xml --coverage-text

notifications:
    email:
        tom@rawphp.org